package com.znd.ei.computing.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.GetMapping;

import com.znd.ei.computing.dao.ComputingRepository;
import com.znd.ei.computing.domain.Compute;

@Controller
// This means that this class is a Controller
@RequestMapping(path = "/computing")
// This means URL's start with /demo (after Application path)
public class ComputingController {
	@Autowired
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ComputingRepository computeRepository;

	@GetMapping(path = "/add")
	// Map ONLY GET Requests
	public @ResponseBody String addCompute(@RequestParam String name,
			@RequestParam String target) {
		// @ResponseBody means the returned String is the response, not a view
		// name
		// @RequestParam means it is a parameter from the GET or POST request

		Compute n = new Compute();
		n.setName(name);
		n.setTarget(target);
		computeRepository.save(n);
		return "Saved";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Compute> getAllComputes() {
		// This returns a JSON or XML with the users
		return computeRepository.findAll();
	}
}
