#pragma once

static	tagMemDBField	g_PGSubRegionFieldArray[]=
{
	{	PG_SUBREGION_RESOURCEID,		"ResourceID",		"资源Id",										MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_SUBREGION_NAME,				"Name",				"名称",											MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_SUBREGION_DESC,				"Description",		"描述",											MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_SUBREGION_REGIONTYPE,		"RegionType",		"分区类型",										MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumSubRegion_RegionType)/sizeof(tagMemDBEnumPair),	g_PGEnumSubRegion_RegionType,	},
	{	PG_SUBREGION_TOTALGENP,			"TotalGenP",		"总发电有功(兆瓦)",								MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_TOTALGENQ,			"TotalGenQ",		"总发电无功(兆乏)",								MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_TOTALLOADP,		"TotalLoadP",		"总负荷有功(兆瓦)",								MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_TOTALLOADQ,		"TotalLoadQ",		"总负荷无功(兆乏)",								MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_TOTALCAP,			"TotalCap",			"总电容无功(兆乏)",								MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_TOTALREAC,			"TotalReac",		"总电抗无功(兆乏)",								MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_TOTALLOSSP,		"TotalLossP",		"总网损有功(兆瓦)",								MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_TOTALLOSSQ,		"TotalLossQ",		"总网损无功(兆乏)",								MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_GENFATCTOR,		"GenFatctor",		"发电功率因数",									MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_LOADFATCTOR,		"LoadFatctor",		"负荷功率因数",									MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_RO_CUSTOMERNUM,	"ro_customernum",	"分区用户总数",									MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_ACI,			"ro_aci",			"用户年停电次数(次/年)",						MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_CID,			"ro_cid",			"用户年停电时间(小时/年)",						MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_SAIFI,			"ro_saifi",			"分区年均停电次数(次/户.年)",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_SAIDI,			"ro_saidi",			"分区年均停电时间(小时/户.年)",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_ASAI,			"ro_asai",			"综合平均理论供电可用率",						MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_ENS,			"ro_ens",			"分区年均停电电量(兆瓦时/年)",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_AENS,			"ro_aens",			"用户年均停电电量(兆瓦时/户.年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_MIC,			"ro_mic",			"分区停电平均用户数(户/次)",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_MID,			"ro_mid",			"分区停电平均持续时间(小时/次)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_F_ACI,			"ro_f_aci",			"用户年故障停电次数(次/年)",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_F_CID,			"ro_f_cid",			"用户年故障停电时间(小时/年)",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_F_SAIFI,		"ro_f_saifi",		"分区年均故障停电次数(次/户.年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_F_SAIDI,		"ro_f_saidi",		"分区年均故障停电时间(小时/户.年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_F_ASAI,			"ro_f_asai",		"故障平均理论供电可用率",						MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_F_ENS,			"ro_f_ens",			"分区年均故障停电电量(兆瓦时/年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_F_AENS,			"ro_f_aens",		"用户年均故障停电电量(兆瓦时/户.年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_F_MIC,			"ro_f_mic",			"分区故障停电平均用户数(户/次)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_F_MID,			"ro_f_mid",			"分区故障停电平均持续时间(小时/次)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_C_ACI,			"ro_c_aci",			"用户年故障综合停电次数(次/年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_C_CID,			"ro_c_cid",			"用户年故障综合停电时间(小时/年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_C_SAIFI,		"ro_c_saifi",		"分区年均故障综合停电次数(次/户.年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_C_SAIDI,		"ro_c_saidi",		"分区年均故障综合停电时间(小时/户.年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_C_ASAI,			"ro_c_asai",		"故障综合平均理论供电可用率",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_C_ENS,			"ro_c_ens",			"分区年均故障综合停电电量(兆瓦时/年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_C_AENS,			"ro_c_aens",		"用户年均故障综合停电电量(兆瓦时/户.年)",		MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_C_MIC,			"ro_c_mic",			"分区故障综合停电平均用户数(户/次)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_C_MID,			"ro_c_mid",			"分区故障综合停电平均持续时间(小时/次)",		MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_A_ACI,			"ro_a_aci",			"用户年预安排停电次数(次/年)",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_A_CID,			"ro_a_cid",			"用户年预安排停电时间(小时/年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_A_SAIFI,		"ro_a_saifi",		"分区年均预安排停电次数(次/户.年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_A_SAIDI,		"ro_a_saidi",		"分区年均预安排停电时间(小时/户.年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_A_ASAI,			"ro_a_asai",		"预安排平均理论供电可用率",						MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_A_ENS,			"ro_a_ens",			"分区年均预安排停电电量(兆瓦时/年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_A_AENS,			"ro_a_aens",		"用户年均预安排停电电量(兆瓦时/户.年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_A_MIC,			"ro_a_mic",			"分区预安排停电平均用户数(户/次)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_RO_A_MID,			"ro_a_mid",			"分区预安排停电平均持续时间(小时/次)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SUBREGION_EO_RCOEF,			"eo_rcoef",			"最小回报系数",									MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_EO_LOSSCOST,		"eo_losscost",		"线损成本(万元)",								MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_EO_RELICOST,		"eo_relicost",		"可靠性成本(万元)",								MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_EO_FUNDCOST,		"eo_fundcost",		"资金成本(万元)",								MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBREGION_EO_INCOME,			"eo_income",		"(投产还贷期)年最小收入(万元)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
};

static	tagMemDBField	g_PGSubstationEntityFieldArray[]=
{
	{	PG_SUBSTATIONENTITY_RESOURCEID,			"ResourceID",					"资源ID",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_SUBSTATION,			"Substation",					"厂站名称(虚拟)",					MDBFieldCategoryAid,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_VOLTAGELEVEL,		"VoltageLevel",					"电压等级",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_SUBSTATIONENTITY_NAME,				"Name",							"名称",								MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_HIGHVOLTAGELEVEL,	"HighVoltageLevel",				"最高电压等级",						MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_SUBSTATIONENTITY_CONNECTIVITYNODE,	"ConnectivityNode",				"节点(物理)",						MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_SUBSTATIONTYPE,		"SubstationType",				"厂站类型",							MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumSubstationEntity_Type)/sizeof(tagMemDBEnumPair),	g_PGEnumSubstationEntity_Type,	},
	{	PG_SUBSTATIONENTITY_COMPONENT,			"Component",					"变电站容量构成",					MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_SUBSTATIONENTITY_MVACAPACITY,		"MvaCapacity",					"容量(兆伏安)",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_GENP,				"GenP",							"发电有功(兆瓦)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_GENQ,				"GenQ",							"发电无功(兆乏)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_PLANVAMP,			"PlanVAmp",						"计划电压(标幺)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_LOADP,				"LoadP",						"负荷(兆瓦)",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_LOADFACTOR,			"LoadFactor",					"负荷功率因数",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_SHUNTCAP,			"Shuntcap",						"无功补偿(兆乏)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_HEATINGLOAD,		"HeatingLoad",					"热负荷功率(兆瓦)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_REFRIGERATIONLOAD,	"RefrigerationLoad",			"冷负荷功率(兆瓦)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_AUTOFORMTRAN,		"AutoFormTran",					"自动生成变压器",					MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumNoYes)/sizeof(tagMemDBEnumPair),							g_PGEnumNoYes,						},
	{	PG_SUBSTATIONENTITY_EQX1,				"EqX",							"等值正序电抗(标幺)(电源站)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_EQX0,				"EqX0",							"等值零序电抗(标幺)(电源站)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_BPA_GENBUS,			"BPAGenBus",					"BPA模型发电机母线",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_SUBSTATIONENTITY_BPA_GENVOLT,		"BPAGenVolt",					"BPA模型发电机电压",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_TOTALBAY,			"TotalBay",						"间隔总数(电源站)",					MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_SUBSTATIONENTITY_FREEBAY,			"FreeBay",						"空闲间隔数(电源站)",				MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_SUBSTATIONENTITY_TOTALOUTLINE,		"TotalOutline",					"出线间隔总数(电源站)",				MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_SUBSTATIONENTITY_INUSEOUTLINE,		"InuseOutline",					"已出线间隔数(电源站)",				MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RI_RERR,			"ri_Rerr",						"故障率(次/台.年)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RI_TREP,			"ri_Trep",						"修复时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RI_RCHK,			"ri_Rchk",						"计划检修率(次/台.年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RI_TCHK,			"ri_Tchk",						"检修时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RI_TFLOC,			"ri_Tfloc",						"故障定位隔离时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RI_CUSTOMER,		"ri_Customer",					"用户数",							MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RI_LOAD_RERR,		"ri_Load_Rerr",					"配出负荷故障率(次/台.年)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RI_LOAD_TREP,		"ri_Load_Trep",					"配出负荷修复时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RI_LOAD_RCHK,		"ri_Load_Rchk",					"配出负荷计划检修率(次/台.年)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RI_LOAD_TCHK,		"ri_Load_Tchk",					"配出负荷检修时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RI_IDEALFLOCTIME,	"IdealFaultIndicatorTime",		"理想通讯条件下故障定位决策时间",	MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_EI_INVEST,			"ei_Invest",					"投资费用(万元/台)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_EI_CONSTLOSS,		"ei_ConstLoss",					"每次固定停电损失(万元/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_EI_EVALRATIO,		"ei_EvalRatio",					"单位电能停电损失",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},

	{	PG_SUBSTATIONENTITY_RW_TUNING1,			"RW_Tuning1",					"转速保护整定1(标幺)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RW_TUNING2,			"RW_Tuning2",					"转速保护整定2(标幺)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RW_DELAY1,			"RW_Delay1",					"转速保护延时1(周)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RW_DELAY2,			"RW_Delay2",					"转速保护延时2(周)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RW_PLATE,			"RW_Plate",						"转速保护压板",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumPlateStatus)/sizeof(tagMemDBEnumPair),			g_PGEnumPlateStatus,	},

	{	PG_SUBSTATIONENTITY_RE_TUNING1,			"RE_Tuning1",					"电压保护整定1(标幺)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RE_TUNING2,			"RE_Tuning2",					"电压保护整定2(标幺)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RE_DELAY1,			"RE_Delay1",					"电压保护延时1(周)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RE_DELAY2,			"RE_Delay2",					"电压保护延时2(周)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_RE_PLATE,			"RE_Plate",						"电压保护压板",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumPlateStatus)/sizeof(tagMemDBEnumPair),			g_PGEnumPlateStatus,	},

	{	PG_SUBSTATIONENTITY_ISLAND,				"Island",						"电岛",								MDBFieldCategoryTopo,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_NODEPTR,			"NodePtr",						"节点索引",							MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_P,					"P",							"下网有功(兆瓦)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_Q,					"Q",							"下网无功(兆乏)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_V,					"V",							"电压(千伏)",						MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_D,					"D",							"功角(度)",							MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_EO_LOSS,			"eo_loss",						"停电综合损失(万元)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_SCC,				"scc",							"短路电流(安培)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_SA_RESULT,			"sa_Result",					"N-1通过情况",						MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumSaResult)/sizeof(tagMemDBEnumPair),	g_PGEnumSaResult,	},
	{	PG_SUBSTATIONENTITY_SA_ISLAND,			"sa_Island",					"N-1形成孤岛",						MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumNoYes)/sizeof(tagMemDBEnumPair),		g_PGEnumNoYes,		},
	{	PG_SUBSTATIONENTITY_SA_FAILURE,			"sa_Failure",					"N-1负荷损失(兆伏安)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_SUBSTATIONENTITY_SA_OUTAGES,			"sa_Outages",					"N-1设备负荷损失(兆瓦)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
};

static	tagMemDBField	g_PGBranchSegmentFieldArray[]=
{
	{	PG_BRANCHSEGMENT_RESOURCEID,		"ResourceID",			"资源Id",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_BRANCHSEGMENT_NAME,				"Name",					"名称",								MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_BRANCHSEGMENT_ACLINESEGMENT,		"ACLineSegment",		"所属线路",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_BRANCHSEGMENT_SUBSTATIONSIDE,	"SubstationSide",		"所接线路侧",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_BRANCHSEGMENT_TOWERID,			"TowerID",				"接入杆塔/电缆头编号",				MDBFieldCategoryParam,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_VOLTAGELEVEL,		"VoltageLevel",			"电压等级",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_BRANCHSEGMENT_LINETYPE,			"LineType",				"架空/电缆",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_BRANCHSEGMENT_LINEMODEL,			"LineModel",			"线路型号",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_BRANCHSEGMENT_LENGTH,			"Length",				"线路长度(千米)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_STATUS,			"Status",				"状态",								MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumCloseOpenStatus)/sizeof(tagMemDBEnumPair),					g_PGEnumCloseOpenStatus,	},
	{	PG_BRANCHSEGMENT_LOADP,				"LoadP",				"线路负荷功率(兆瓦)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_LOADFACTOR,		"LoadFactor",			"线路负荷功率因数",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_LOADCAP,			"LoadCap",				"线上无功补偿容量(兆乏)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_HEATINGLOAD,		"HeatingLoad",			"线路热负荷功率(兆瓦)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_REFRIGERATIONLOAD,	"RefrigerationLoad",	"线路冷负荷功率(兆瓦)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RATECUR,			"RatedCur",				"电流限值(安)",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RATEMVA,			"RatedMva",				"功率限值(兆瓦)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_UNITR,				"UnitR",				"单位电阻(欧姆)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_UNITX,				"UnitX",				"单位电抗(欧姆)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_UNITG,				"UnitG",				"单位电导(西门子)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_UNITB,				"UnitB",				"单位电纳(西门子)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_UNITRERR,		"ri_UnitRerr",			"单位故障率(次/千米.年)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_UNITTREP,		"ri_UnitTrep",			"单位修复时间(小时/次)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_UNITRCHK,		"ri_UnitRchk",			"单位计划检修率(次/千米.年)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_UNITTCHK,		"ri_UnitTchk",			"单位检修时间(小时/次)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_EI_UNITINVEST,		"ei_UnitInvest",		"单位投资费用(万元/千米)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_R,					"R",					"电阻(标幺)",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_X,					"X",					"电抗(标幺)",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_G,					"G",					"电导(标幺)",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_B,					"B",					"电纳(标幺)",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_R0,				"R0",					"零序电阻(标幺)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_X0,				"X0",					"零序电抗(标幺)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_B0,				"B0",					"零序电纳(标幺)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_RERR,			"ri_Rerr",				"分支线故障率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_TREP,			"ri_Trep",				"分支线修复时间(时间/次)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_RCHK,			"ri_Rchk",				"分支线计划检修率(次/年)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_TCHK,			"ri_Tchk",				"分支线检修时间(时间/次)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_TFLOC,			"ri_Tfloc",				"分支线故障定位隔离时间",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_CUSTOMER,		"ri_Customer",			"用户数",							MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_LOAD_RERR,		"ri_Load_Rerr",			"配出负荷故障率(次/年)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_LOAD_TREP,		"ri_Load_Trep",			"配出负荷修复时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_LOAD_RCHK,		"ri_Load_Rchk",			"配出负荷计划检修率(次/年)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_LOAD_TCHK,		"ri_Load_Tchk",			"配出负荷检修时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_EI_INVEST,			"ei_Invest",			"投资费用(万元)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_EI_CONSTLOSS,		"ei_ConstLoss",			"每次固定停电损失(万元/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_EI_EVALRATIO,		"ei_EvalRatio",			"单位电能停电损失",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_VD_RSCC1,			"vd_RScc1",				"单相接地频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_VD_RSCC2,			"vd_RScc2",				"相间短路频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_VD_RSCC3,			"vd_RScc3",				"三相短路频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_VD_RSCC4,			"vd_RScc4",				"两相接地频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},

	{	PG_BRANCHSEGMENT_BRANCHBREAKING,	"BranchBreaking",		"分支线出口开断设备",				MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumNoYes)/sizeof(tagMemDBEnumPair),				g_PGEnumNoYes,					},
	{	PG_BRANCHSEGMENT_BREAKINGTYPE,		"BreakingType",			"分支线出口开断设备类型",			MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumBreaker_BreakerType)/sizeof(tagMemDBEnumPair),	g_PGEnumBreaker_BreakerType,	},
	{	PG_BRANCHSEGMENT_RI_SW_RERR,		"ri_sw_rerr",			"分支线出口开关故障率(次/年)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_SW_TREP,		"ri_sw_trep",			"分支线出口开关修复时间(时间/次)",	MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_SW_RCHK,		"ri_sw_rchk",			"分支线出口开关计划检修率(次/年)",	MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_SW_TCHK,		"ri_sw_tchk",			"分支线出口开关检修时间(时间/次)",	MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RI_SW_TFLOC,		"ri_sw_tfloc",			"分支线出口开关故障定位隔离时间",	MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},

	{	PG_BRANCHSEGMENT_P,					"P",					"有功(兆瓦)",						MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_Q,					"Q",					"无功(兆乏)",						MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_A,					"A",					"电流(安培)",						MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_LOSSP,				"LossP",				"损耗有功(兆瓦)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_LOSSQ,				"LossQ",				"损耗无功(兆乏)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_RO_ENS,			"ro_ens",				"年均停电电量(兆瓦时/年)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_EO_LOSS,			"eo_loss",				"停电综合损失(万元)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_SA_RESULT,			"sa_Result",			"N-1通过情况",						MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumSaResult)/sizeof(tagMemDBEnumPair),	g_PGEnumSaResult, },
	{	PG_BRANCHSEGMENT_SA_ISLAND,			"sa_Island",			"N-1形成孤岛",						MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumNoYes)/sizeof(tagMemDBEnumPair),		g_PGEnumNoYes,	},
	{	PG_BRANCHSEGMENT_SA_FAILURE,		"sa_Failure",			"N-1负荷损失(兆伏安)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_BRANCHSEGMENT_SA_SHIFTNODE,		"sa_ShiftNode",			"N-1转电节点",						MDBFieldCategoryOutput,	MDB_INT,	sizeof(int),			0,	NULL,	},
};

static	tagMemDBField	g_PGDistributionSwitchFieldArray[]=
{
	{	PG_DISTRIBUTIONSWITCH_RESOURCEID,			"ResourceID",			"资源ID",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_SUBSTATION,			"Substation",			"厂站名称(虚拟)",					MDBFieldCategoryAid,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_VOLTAGELEVEL,			"VoltageLevel",			"电压等级",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_NAME,					"Name",					"名称",								MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_CONNECTIVITYNODE,		"ConnectivityNode",		"节点",								MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_TYPE,					"Type",					"设备类型",							MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumDSwitchType)/sizeof(tagMemDBEnumPair),	g_PGEnumDSwitchType, },
	{	PG_DISTRIBUTIONSWITCH_MODEL,				"Model",				"型号",								MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_LOADP,				"LoadP",				"负荷(兆瓦)",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_LOADFACTOR,			"LoadFactor",			"负荷功率因数",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_SHUNTCAP,				"ShuntCap",				"无功补偿(兆乏)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_HEATINGLOAD,			"HeatingLoad",			"热负荷功率(兆瓦)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_REFRIGERATIONLOAD,	"RefrigerationLoad",	"冷负荷功率(兆瓦)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_RI_RERR,				"ri_Rerr",				"故障率(次/台.年)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_RI_TREP,				"ri_Trep",				"修复时间(时间/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_RI_RCHK,				"ri_Rchk",				"计划检修率(次/台.年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_RI_TCHK,				"ri_Tchk",				"检修时间(时间/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_RI_TFLOC,				"ri_Tfloc",				"故障定位隔离时间(小时)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_RI_CUSTOMER,			"ri_Customer",			"用户数",							MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_RI_LOAD_RERR,			"ri_Load_Rerr",			"配出负荷故障率(次/台.年)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_RI_LOAD_TREP,			"ri_Load_Trep",			"配出负荷修复时间(时间/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_RI_LOAD_RCHK,			"ri_Load_Rchk",			"配出负荷计划检修率(次/台.年)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_RI_LOAD_TCHK,			"ri_Load_Tchk",			"配出负荷检修时间(时间/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_EI_INVEST,			"ei_Invest",			"投资费用(万元)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_EI_CONSTLOSS,			"ei_ConstLoss",			"每次固定停电损失(万元/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_EI_EVALRATIO,			"ei_EvalRatio",			"单位电能停电损失",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_VD_RSCC1,				"vd_RScc1",				"单相接地频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_VD_RSCC2,				"vd_RScc2",				"相间短路频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_VD_RSCC3,				"vd_RScc3",				"三相短路频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_VD_RSCC4,				"vd_RScc4",				"两相接地频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},

	{	PG_DISTRIBUTIONSWITCH_ISLAND,				"Island",				"电岛",								MDBFieldCategoryTopo,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_NODEPTR,				"NodePtr",				"节点索引",							MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_V,					"V",					"电压(千伏)",						MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_D,					"D",					"功角(度)",							MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_SCC,					"Scc",					"短路电流(安培)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_SA_RESULT,			"sa_Result",			"N-1通过情况",						MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumSaResult)/sizeof(tagMemDBEnumPair),	g_PGEnumSaResult,	},
	{	PG_DISTRIBUTIONSWITCH_SA_ISLAND,			"sa_Island",			"N-1形成孤岛",						MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumNoYes)/sizeof(tagMemDBEnumPair),		g_PGEnumNoYes,		},
	{	PG_DISTRIBUTIONSWITCH_SA_FAILURE,			"sa_Failure",			"N-1负荷损失(兆伏安)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_SA_OUTAGES,			"sa_Outages",			"N-1设备负荷损失(兆瓦)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_EO_LOSS,				"eo_loss",				"停电综合损失(万元)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_OUTLINENUM,			"OutLineNum",			"出线规模(回)",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_DISTRIBUTIONSWITCH_INUSEOUTLINE,			"InuseOutline",			"已出线间隔",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
};

static	tagMemDBField	g_PGDistributionLoadFieldArray[]=
{
	{	PG_DISTRIBUTIONLOAD_RESOURCEID,			"ResourceID",			"资源ID",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_SUBSTATION,			"Substation",			"厂站名称(虚拟)",					MDBFieldCategoryAid,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_VOLTAGELEVEL,		"VoltageLevel",			"电压等级",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_NAME,				"Name",					"名称",								MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_USERID,				"UserId",				"用户编号",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_SUBSTATIONENTITY,	"SubstationEntity",		"所属容器(厂站、开闭所等)",			MDBFieldCategoryAid,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_CONNECTIVITYNODE,	"ConnectivityNode",		"节点",								MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_TYPE,				"Type",					"设备类型",							MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumDEnergyConsumerType)/sizeof(tagMemDBEnumPair),	g_PGEnumDEnergyConsumerType, },
	{	PG_DISTRIBUTIONLOAD_MODEL,				"Model",				"型号",								MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_RATECAPACITY,		"RateCapacity",			"额定容量(千伏安)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_LOADRATIO,			"LoadRatio",			"负载率",							MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_LOADP,				"LoadP",				"负荷(兆瓦)",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_LOADFACTOR,			"LoadFactor",			"负荷功率因数",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_SHUNTCAP,			"ShuntCap",				"无功补偿(兆乏)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_HEATINGLOAD,		"HeatingLoad",			"热负荷功率(兆瓦)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_REFRIGERATIONLOAD,	"RefrigerationLoad",	"冷负荷功率(兆瓦)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_RI_RERR,			"ri_Rerr",				"故障率(次/台.年)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_RI_TREP,			"ri_Trep",				"修复时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_RI_RCHK,			"ri_Rchk",				"计划检修率(次/台.年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_RI_TCHK,			"ri_Tchk",				"检修时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_RI_TFLOC,			"ri_Tfloc",				"故障定位隔离时间(小时)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_RI_CUSTOMER,		"ri_Customer",			"用户数",							MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_RI_LOAD_RERR,		"ri_Load_Rerr",			"配出负荷故障率(次/台.年)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_RI_LOAD_TREP,		"ri_Load_Trep",			"配出负荷修复时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_RI_LOAD_RCHK,		"ri_Load_Rchk",			"配出负荷计划检修率(次/台.年)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_RI_LOAD_TCHK,		"ri_Load_Tchk",			"配出负荷检修时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_EI_INVEST,			"ei_Invest",			"投资费用(万元/kVA)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_EI_CONSTLOSS,		"ei_ConstLoss",			"每次固定停电损失(万元/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_EI_EVALRATIO,		"ei_EvalRatio",			"单位电能停电损失",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_VD_RSCC1,			"vd_RScc1",				"单相接地频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_VD_RSCC2,			"vd_RScc2",				"相间短路频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_VD_RSCC3,			"vd_RScc3",				"三相短路频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_VD_RSCC4,			"vd_RScc4",				"两相接地频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},

	{	PG_DISTRIBUTIONLOAD_ISLAND,				"Island",				"电岛",								MDBFieldCategoryTopo,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_NODEPTR,			"NodePtr",				"节点索引",							MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_V,					"V",					"电压(千伏)",						MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_D,					"D",					"功角(度)",							MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_EO_LOSS,			"eo_loss",				"停电综合损失(万元)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_SCC,				"scc",					"短路电流(安培)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_SA_RESULT,			"sa_Result",			"N-1通过情况",						MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumSaResult)/sizeof(tagMemDBEnumPair),	g_PGEnumSaResult, },
	{	PG_DISTRIBUTIONLOAD_SA_ISLAND,			"sa_Island",			"N-1形成孤岛",						MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumNoYes)/sizeof(tagMemDBEnumPair),		g_PGEnumNoYes,	},
	{	PG_DISTRIBUTIONLOAD_SA_FAILURE,			"sa_Failure",			"N-1负荷损失(兆伏安)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONLOAD_SA_OUTAGES,			"sa_Outages",			"N-1设备负荷损失(兆瓦)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
};

static	tagMemDBField	g_PGDistributionBreakerFieldArray[]=
{
	{	PG_DISTRIBUTIONBREAKER_RESOURCEID,			"ResourceID",			"资源ID",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_SUBSTATION,			"Substation",			"厂站名称(虚拟)",					MDBFieldCategoryAid,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_VOLTAGELEVEL,		"VoltageLevel",			"电压等级",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_NAME,				"Name",					"名称",								MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_SUBSTATIONENTITY,	"SubstationEntity",		"所属容器(厂站、开闭所等)",			MDBFieldCategoryAid,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_CONNECTIVITYNODEI,	"ConnectivityNodeI",	"起节点",							MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_CONNECTIVITYNODEJ,	"ConnectivityNodeZ",	"终节点",							MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_MODEL,				"Model",				"设备型号",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_BREAKERTYPE,			"BreakerType",			"开关类型",							MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumBreaker_BreakerType)/sizeof(tagMemDBEnumPair),	g_PGEnumBreaker_BreakerType,	},
	{	PG_DISTRIBUTIONBREAKER_CONSTOPEN,			"ConstOpen",			"停运设备",							MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumNoYes)/sizeof(tagMemDBEnumPair),					g_PGEnumNoYes,	},
	{	PG_DISTRIBUTIONBREAKER_STATUS,				"Status",				"设备运行状态",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumCloseOpenStatus)/sizeof(tagMemDBEnumPair),		g_PGEnumCloseOpenStatus,	},
	{	PG_DISTRIBUTIONBREAKER_RI_RERR,				"ri_Rerr",				"故障率(次/台.年)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_RI_TREP,				"ri_Trep",				"修复时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_RI_RCHK,				"ri_Rchk",				"计划检修率(次/台.年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_RI_TCHK,				"ri_Tchk",				"检修时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_RI_TFLOC,			"ri_Tfloc",				"故障定位隔离时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_RI_RSWITCH,			"ri_RSwitch",			"操作成功率",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_RI_TSWITCH,			"ri_TSwitch",			"操作时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_RI_TDELAY,			"ri_Tdelay",			"延时时间(负荷开关/重合器)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_RI_CUSTOMER,			"ri_Customer",			"用户数",							MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_RI_LOAD_RERR,		"ri_Load_Rerr",			"配出负荷故障率(次/台.年)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_RI_LOAD_TREP,		"ri_Load_Trep",			"配出负荷修复时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_RI_LOAD_RCHK,		"ri_Load_Rchk",			"配出负荷计划检修率(次/台.年)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_RI_LOAD_TCHK,		"ri_Load_Tchk",			"配出负荷检修时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_EI_INVEST,			"ei_Invest",			"投资费用(万/台)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_VD_RSCC1,			"vd_RScc1",				"单相接地频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_VD_RSCC2,			"vd_RScc2",				"相间短路频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_VD_RSCC3,			"vd_RScc3",				"三相短路频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_VD_RSCC4,			"vd_RScc4",				"两相接地频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},

	{	PG_DISTRIBUTIONBREAKER_ISLAND,				"Island",				"电岛",								MDBFieldCategoryTopo,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_SCC,					"scc",					"短路电流(安培)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_SA_RESULT,			"sa_Result",			"N-1通过情况",						MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumSaResult)/sizeof(tagMemDBEnumPair),	g_PGEnumSaResult, },
	{	PG_DISTRIBUTIONBREAKER_SA_ISLAND,			"sa_Island",			"N-1形成孤岛",						MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumNoYes)/sizeof(tagMemDBEnumPair),		g_PGEnumNoYes,	},
	{	PG_DISTRIBUTIONBREAKER_SA_FAILURE,			"sa_Failure",			"N-1负荷损失(兆伏安)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_SA_OUTAGES,			"sa_Outages",			"N-1设备负荷损失(兆瓦)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_NODEIPTR,			"NodeIPtr",				"起节点索引",						MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DISTRIBUTIONBREAKER_NODEJPTR,			"NodeJPtr",				"终节点索引",						MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
};

static	tagMemDBField	g_PGDistributionDotFieldArray[]=
{
	{	PG_DISTRIBUTIONDOT_RESOURCEID,			"ResourceID",		"资源ID",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_SUBSTATION,			"Substation",		"厂站名称(虚拟)",					MDBFieldCategoryAid,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_VOLTAGELEVEL,		"VoltageLevel",		"电压等级",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_NAME,				"Name",				"名称",								MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_SUBSTATIONENTITY,	"SubstationEntity",	"所属容器(厂站、开闭所等)",			MDBFieldCategoryAid,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_CONNECTIVITYNODE,	"ConnectivityNode",	"节点",								MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_TYPE,				"Type",				"设备类型",							MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumDJunctionPoleType)/sizeof(tagMemDBEnumPair),	g_PGEnumDJunctionPoleType, },
	{	PG_DISTRIBUTIONDOT_LOADP,				"LoadP",			"负荷(兆瓦)",						MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_LOADFACTOR,			"LoadFactor",		"功率因数",							MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_SHUNTCAP,			"ShuntCap",			"无功补偿(兆乏)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_HEATINGLOAD,			"HeatingLoad",		"热负荷功率(兆瓦)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_REFRIGERATIONLOAD,	"RefrigerationLoad","冷负荷功率(兆瓦)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_RI_RERR,				"ri_Rerr",			"故障率(次/台.年)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_RI_TREP,				"ri_Trep",			"修复时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_RI_RCHK,				"ri_Rchk",			"计划检修率(次/台.年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_RI_TCHK,				"ri_Tchk",			"检修时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_RI_TFLOC,			"ri_Tfloc",			"故障定位隔离时间(小时)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_RI_CUSTOMER,			"ri_Customer",		"用户数",							MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_RI_LOAD_RERR,		"ri_Load_Rerr",		"配出负荷故障率(次/台.年)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_RI_LOAD_TREP,		"ri_Load_Trep",		"配出负荷修复时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_RI_LOAD_RCHK,		"ri_Load_Rchk",		"配出负荷计划检修率(次/台.年)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_RI_LOAD_TCHK,		"ri_Load_Tchk",		"配出负荷检修时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_EI_INVEST,			"ei_Invest",		"投资费用(万元)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_EI_CONSTLOSS,		"ei_ConstLoss",		"每次固定停电损失(万元/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_EI_EVALRATIO,		"ei_EvalRatio",		"单位电能停电损失",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_VD_RSCC1,			"vd_RScc1",			"单相接地频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_VD_RSCC2,			"vd_RScc2",			"相间短路频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_VD_RSCC3,			"vd_RScc3",			"三相短路频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_VD_RSCC4,			"vd_RScc4",			"两相接地频率(次/年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},

	{	PG_DISTRIBUTIONDOT_ISLAND,				"Island",			"电岛",								MDBFieldCategoryTopo,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_NODEPTR,				"NodePtr",			"节点索引",							MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_V,					"V",				"电压(千伏)",						MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_D,					"D",				"功角(度)",							MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_EO_LOSS,				"eo_loss",			"停电综合损失(万元)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_SCC,					"scc",				"短路电流(安培)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_SA_RESULT,			"sa_Result",		"N-1通过情况",						MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumSaResult)/sizeof(tagMemDBEnumPair),			g_PGEnumSaResult,		},
	{	PG_DISTRIBUTIONDOT_SA_ISLAND,			"sa_Island",		"N-1形成孤岛",						MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumNoYes)/sizeof(tagMemDBEnumPair),				g_PGEnumNoYes,			},
	{	PG_DISTRIBUTIONDOT_SA_FAILURE,			"sa_Failure",		"N-1负荷损失(兆伏安)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DISTRIBUTIONDOT_SA_OUTAGES,			"sa_Outages",		"N-1设备负荷损失(兆瓦)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
};

static	tagMemDBField	g_PGLandPlotFieldArray[]=
{
	{	PG_LANDPLOT_RESOURCEID,			"ResourceID",			"资源ID",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_LANDPLOT_NAME,				"Name",					"地块名称",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_LANDPLOT_LOCATEX,			"LocateX",				"中心点坐标X",						MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_LANDPLOT_LOCATEY,			"LocateY",				"中心点坐标Y",						MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_LANDPLOT_LANDAREA,			"LandArea",				"地块面积(平米)",					MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_LANDPLOT_BUILDINGAREA,		"BuildingArea",			"建筑面积(平米)",					MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_LANDPLOT_LANDINDEX,			"LandIndex",			"指标类型",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_LANDPLOT_LANDTYPE,			"LandType",				"地块类型",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_LANDPLOT_SAMERATE,			"Samerate",				"同时率",							MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_LANDPLOT_DENSITY,			"Density",				"负荷密度(瓦/平米)",				MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_LANDPLOT_DEMAND,				"Demand",				"需用系数",							MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_LANDPLOT_VOLUME,				"Volume",				"容积率",							MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_LANDPLOT_METATYPE,			"MetaType",				"图元类型",							MDBFieldCategoryParam,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_LANDPLOT_LAYER,				"Layer",				"地块层号",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_LANDPLOT_COLOR,				"Color",				"地块颜色",							MDBFieldCategoryParam,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_LANDPLOT_DENSITYLOAD,		"DensityLoad",			"负荷密度法(兆瓦)",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_LANDPLOT_DISTRIBLOAD,		"DistribLoad",			"分布预测法(兆瓦)",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_LANDPLOT_INCALCULATE,		"InCalculate",			"参与预测",							MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
};

static	tagMemDBField	g_PGPipeFieldArray[]=
{
	{	PG_PIPE_RESOURCEID,			"ResourceID",		"资源ID",					MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_NAME,				"Name",				"名称",						MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_MODEL,				"Model",			"规格",						MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LENGTH,				"Length",			"长度(千米)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_PIPE_EI_UNITINVEST,		"ei_UnitInvest",	"单位投资费用(万元/千米)",	MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_PIPE_BUILDDATE,			"BuildDate",		"建造日期(年月日)",			MDBFieldCategoryParam,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_PIPE_REBUILDDATE,		"ReBuildDate",		"改造日期(年月日)",			MDBFieldCategoryParam,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_PIPE_OUTAGEDATE,			"OutageDate",		"停运日期(年月日)",			MDBFieldCategoryParam,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_PIPE_RUNTIMESPAN,		"TimeSpan",			"运行时间",					MDBFieldCategoryParam,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_PIPE_PLANCHARACTER,		"PlanCharacter",	"规划性质",					MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumDPlanCharacter)/sizeof(tagMemDBEnumPair),	g_PGEnumDPlanCharacter,	},
	{	PG_PIPE_PROJCHARACTER,		"ProjCharacter",	"工程性质",					MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumDProjCharacter)/sizeof(tagMemDBEnumPair),	g_PGEnumDProjCharacter,	},
	{	PG_PIPE_VOLTAGELEVELH,		"VoltageLevelH",	"高压电压等级",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_PIPE_VOLTAGELEVELM,		"VoltageLevelM",	"中压电压等级",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_PIPE_VOLTAGELEVELL,		"VoltageLevelL",	"低压电压等级",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_PIPE_HV2MV,				"HV2MV",			"高压到中压换算",			MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_PIPE_HV2LV,				"HV2LV",			"高压到低压换算",			MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_PIPE_MV2LV,				"MV2LV",			"中压到低压换算",			MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_PIPE_MAXHVCABLENUM,		"MaxHVCableNum",	"高压电缆容量",				MDBFieldCategoryParam,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_PIPE_MAXMVCABLENUM,		"MaxMVCableNum",	"中压电缆容量",				MDBFieldCategoryParam,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_PIPE_MAXLVCABLENUM,		"MaxLVCableNum",	"低压电缆容量",				MDBFieldCategoryParam,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_PIPE_HVCABLE1,			"HVCable1",			"高压电缆1",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_HVCABLE2,			"HVCable2",			"高压电缆2",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_HVCABLE3,			"HVCable3",			"高压电缆3",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_HVCABLE4,			"HVCable4",			"高压电缆4",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_MVCABLE1,			"MVCable1",			"中压电缆1",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_MVCABLE2,			"MVCable2",			"中压电缆2",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_MVCABLE3,			"MVCable3",			"中压电缆3",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_MVCABLE4,			"MVCable4",			"中压电缆4",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_MVCABLE5,			"MVCable5",			"中压电缆5",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_MVCABLE6,			"MVCable6",			"中压电缆6",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_MVCABLE7,			"MVCable7",			"中压电缆7",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_MVCABLE8,			"MVCable8",			"中压电缆8",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE1,			"LVCable1",			"低压电缆1",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE2,			"LVCable2",			"低压电缆2",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE3,			"LVCable3",			"低压电缆3",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE4,			"LVCable4",			"低压电缆4",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE5,			"LVCable5",			"低压电缆5",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE6,			"LVCable6",			"低压电缆6",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE7,			"LVCable7",			"低压电缆7",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE8,			"LVCable8",			"低压电缆8",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE9,			"LVCable9",			"低压电缆9",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE10,			"LVCable10",		"低压电缆10",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE11,			"LVCable11",		"低压电缆11",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE12,			"LVCable12",		"低压电缆12",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE13,			"LVCable13",		"低压电缆13",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE14,			"LVCable14",		"低压电缆14",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE15,			"LVCable15",		"低压电缆15",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE16,			"LVCable16",		"低压电缆16",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE17,			"LVCable17",		"低压电缆17",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE18,			"LVCable18",		"低压电缆18",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE19,			"LVCable19",		"低压电缆19",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE20,			"LVCable20",		"低压电缆20",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE21,			"LVCable21",		"低压电缆21",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE22,			"LVCable22",		"低压电缆22",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE23,			"LVCable23",		"低压电缆23",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE24,			"LVCable24",		"低压电缆24",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE25,			"LVCable25",		"低压电缆25",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE26,			"LVCable26",		"低压电缆26",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE27,			"LVCable27",		"低压电缆27",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE28,			"LVCable28",		"低压电缆28",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE29,			"LVCable29",		"低压电缆29",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE30,			"LVCable30",		"低压电缆30",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE31,			"LVCable31",		"低压电缆31",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_PIPE_LVCABLE32,			"LVCable32",		"低压电缆32",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
};
