#pragma once

static	tagMemDBField	g_PGTielineFieldArray[]=
{
	{	PG_TIELINE_NAME,				"Name",				"名称",				MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_TIELINE_ICOMPANY,			"iCompany",			"起公司",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_TIELINE_ISUBCONTROLAREA,		"iSubcontrolArea",	"起分区",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_TIELINE_ISUBSTATION,			"iSubstation",		"起厂站",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_TIELINE_IVOLTAGELEVEL,		"iVoltageLevel",	"起电压等级",		MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_TIELINE_ZCOMPANY,			"zCompany",			"终公司",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_TIELINE_ZSUBCONTROLAREA,		"zSubcontrolArea",	"终分区",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_TIELINE_JSUBSTATION,			"zSubstation",		"终厂站",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_TIELINE_JVOLTAGELEVEL,		"zVoltageLevel",	"终电压等级",		MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_TIELINE_CONNECTIVITYNODE,	"ConnectivityNode",	"量测节点",			MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
};

static	tagMemDBField	g_PGSystemReliableField[]=
{
	{	PG_SYSTEMRELIABLE_STEP,				"Step",				"摄动阶数",									MDBFieldCategoryBase,	MDB_SHORT,	sizeof(short),			0,	NULL,	},

	{	PG_SYSTEMRELIABLE_RO_ACI,			"ro_aci",			"用户年停电次数(次/年)",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_CID,			"ro_cid",			"用户年停电时间(小时/年)",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_SAIFI,			"ro_saifi",			"系统年均停电次数(次/户.年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_SAIDI,			"ro_saidi",			"系统年均停电时间(小时/户.年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_ASAI,			"ro_asai",			"综合平均理论供电可用率",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_ENS,			"ro_ens",			"系统年均停电电量(兆瓦时/年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_AENS,			"ro_aens",			"用户年均停电电量(兆瓦时/户.年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_MIC,			"ro_mic",			"系统停电平均用户数(户/次)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_MID,			"ro_mid",			"系统停电平均持续时间(小时/次)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},

	{	PG_SYSTEMRELIABLE_RO_F_ACI,			"ro_f_aci",			"用户年故障停电次数(次/年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_F_CID,			"ro_f_cid",			"用户年故障停电时间(小时/年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_F_SAIFI,		"ro_f_saifi",		"系统年均故障停电次数(次/户.年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_F_SAIDI,		"ro_f_saidi",		"系统年均故障停电时间(小时/户.年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_F_ASAI,		"ro_f_asai",		"故障平均理论供电可用率",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_F_ENS,			"ro_f_ens",			"系统年均故障停电电量(兆瓦时/年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_F_AENS,		"ro_f_aens",		"用户年均故障停电电量(兆瓦时/户.年)",		MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_F_MIC,			"ro_f_mic",			"系统故障停电平均用户数(户/次)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_F_MID,			"ro_f_mid",			"系统故障停电平均持续时间(小时/次)",		MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},

	{	PG_SYSTEMRELIABLE_RO_A_ACI,			"ro_a_aci",			"用户年预安排停电次数(次/年)",				MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_A_CID,			"ro_a_cid",			"用户年预安排停电时间(小时/年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_A_SAIFI,		"ro_a_saifi",		"系统年均预安排停电次数(次/户.年)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_A_SAIDI,		"ro_a_saidi",		"系统年均预安排停电时间(小时/户.年)",		MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_A_ASAI,		"ro_a_asai",		"预安排平均理论供电可用率",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_A_ENS,			"ro_a_ens",			"系统年均预安排停电电量(兆瓦时/年)",		MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_A_AENS,		"ro_a_aens",		"用户年均预安排停电电量(兆瓦时/户.年)",		MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_A_MIC,			"ro_a_mic",			"系统预安排停电平均用户数(户/次)",			MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SYSTEMRELIABLE_RO_A_MID,			"ro_a_mid",			"系统预安排停电平均持续时间(小时/次)",		MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
};

static	tagMemDBField	g_PGEnergyConsumerReliableFieldArray[]=
{
	{	PG_ENERGYCONSUMERRELIABLE_LOAD,			"LoadIdx",		"负荷索引",								MDBFieldCategoryBase,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_STEP,			"Step",			"摄动阶数",								MDBFieldCategoryBase,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_RO_R,			"ro_r",			"年均综合停电次数(次/年)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_RO_T,			"ro_t",			"综合停电平均持续时间(小时/次)",		MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_RO_U,			"ro_u",			"年均综合停电时间",						MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_RO_FR,		"ro_fr",		"年均故障停电次数(次/年)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_RO_FT,		"ro_ft",		"故障停电平均持续时间(小时/次)",		MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_RO_FU,		"ro_fu",		"年均故障停电时间",						MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_RO_AR,		"ro_ar",		"年均预安排停电次数(次/年)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_RO_AT,		"ro_at",		"预安排停电平均持续时间(小时/次)",		MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_RO_AU,		"ro_au",		"年均预安排停电时间",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_RO_CMR,		"ro_cmr",		"年均共模停电次数(次/年)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_RO_CMT,		"ro_cmt",		"共模停电平均持续时间(小时/次)",		MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ENERGYCONSUMERRELIABLE_RO_CMU,		"ro_cmu",		"年均共模停电时间",						MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
};

static	tagMemDBField	g_PGConnLineFieldArray[]=
{
	{	PG_CONNLINE_RESOURCEID,			"ResourceID",		"资源ID",				MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_CONNLINE_SUBSTATION,			"Substation",		"厂站",					MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_CONNLINE_VOLTAGELEVEL,		"VoltageLevel",		"电压等级",				MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_CONNLINE_CONNECTIVITYNODE,	"ConnectivityNode",	"节点",					MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
};

static	tagMemDBField	g_PGHyperLinkFieldArray[]=
{
	{	PG_HYPERLINKS_RESOURCEID,	"ResourceID",		"资源ID",					MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_HYPERLINKS_LINKNAM,		"LinkName",			"连接名称",					MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_HYPERLINKS_LINKGRAPH,	"LinkGraph",		"连接图形",					MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_LONG,		0,	NULL,	},
	{	PG_HYPERLINKS_SHOWBOUND,	"ShowBound",		"显示外框",					MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
};

static	tagMemDBField	g_PGDrawingFieldArray[]=
{
	{	PG_DRAWING_RESOURCEID,		"ResourceID",		"资源ID",					MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DRAWING_NAME,			"Name",				"图纸名称",					MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DRAWING_PATH,			"Path",				"图纸文件",					MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_LONG,		0,	NULL,	},
	{	PG_DRAWING_CREATEDATE,		"CreateDate",		"建立日期",					MDBFieldCategoryParam,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DRAWING_CREATETIME,		"CreateTime",		"建立时间",					MDBFieldCategoryParam,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DRAWING_MODIFYDATE,		"ModifyDate",		"修改日期",					MDBFieldCategoryParam,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DRAWING_MODIFYTIME,		"ModifyTime",		"修改时间",					MDBFieldCategoryParam,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DRAWING_CREATOR,			"Creator",			"图纸创建",					MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_DRAWING_MODIFIER,		"Modifier",			"图纸修改",					MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_DRAWING_REVIEWER,		"Reviewer",			"图纸审核",					MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_DRAWING_APPROVER,		"Approver",			"图纸批准",					MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_DRAWING_PROJECT,			"Project",			"所属项目",					MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_DRAWING_SCHEME,			"Scheme",			"规划设计方案",				MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_DRAWING_VERSION,			"Version",			"图纸版本",					MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
};

static	tagMemDBField	g_PGGraphLayerFieldArray[]=
{
	{	PG_GRAPHLAYER_DRAWING,		"Drawing",		"图纸ID",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_GRAPHLAYER_NAME,			"GeName",		"层名称",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_GRAPHLAYER_COLOR,		"GeColor",		"颜色",							MDBFieldCategoryParam,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_GRAPHLAYER_LINESTYLE,	"GeLineStyle",	"线型",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_GRAPHLAYER_LINEWIDTH,	"GeLineWidth",	"线宽",							MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
};

static	tagMemDBField	g_PGGraphAttrFieldArray[]=
{
	{	PG_GRAPHATTR_DRAWING,		"Drawing",		"图纸ID",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_GRAPHATTR_TABLE,			"GeTable",		"表",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_GRAPHATTR_KEYFIELD,		"KeyField",		"关键字",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_GRAPHATTR_PARENTID,		"GeParentID",	"父ID",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_GRAPHATTR_VISIBLE,		"GeVisible",	"可见",							MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumHideVisibleStatus)/sizeof(tagMemDBEnumPair),				g_PGEnumHideVisibleStatus,	},
	{	PG_GRAPHATTR_LAYER,			"GeLayer",		"层",							MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_GRAPHATTR_FONT,			"GeFont",		"字体名称",						MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_GRAPHATTR_COLOR,			"GeColor",		"颜色",							MDBFieldCategoryParam,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_GRAPHATTR_LINESTYLE,		"GeLineStyle",	"线型",							MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumGraphAttr_LineStyle)/sizeof(tagMemDBEnumPair),	g_PGEnumGraphAttr_LineStyle,	},
	{	PG_GRAPHATTR_LINEWIDTH,		"GeLineWidth",	"线宽",							MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_GRAPHATTR_SIZE,			"GeSize",		"大小",							MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_GRAPHATTR_FLOATPOINT,	"FloatPoint",	"小数位数",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_GRAPHATTR_LOCATIONX,		"LocationX",	"位置坐标X",					MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_GRAPHATTR_LOCATIONY,		"LocationY",	"位置坐标Y",					MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_GRAPHATTR_HAXISX,		"HAxisX",		"横轴法向量X",					MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_GRAPHATTR_HAXISY,		"HAxisY",		"横轴法向量Y",					MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_GRAPHATTR_LAXISX,		"LAxisX",		"纵轴法向量X",					MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_GRAPHATTR_LAXISY,		"LAxisY",		"纵轴法向量Y",					MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_GRAPHATTR_COLORR,		"ColorR",		"Color(R)",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_GRAPHATTR_COLORG,		"ColorG",		"Color(G)",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_GRAPHATTR_COLORB,		"ColorB",		"Color(B)",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
};

static	tagMemDBField	g_PGLineVertexFieldArray[]=
{
	{	PG_LINEVERTEX_DRAWING,		"Drawing",		"图纸ID",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_LINEVERTEX_TABLE,		"GeTable",		"表",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORT,		0,	NULL,	},
	{	PG_LINEVERTEX_PARENT,		"GeParent",		"父ID",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_LINEVERTEX_SERIAL,		"Serial",		"点序号",						MDBFieldCategoryParam,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_LINEVERTEX_VERTEX_X,		"VertexX",		"点坐标X",						MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_LINEVERTEX_VERTEX_Y,		"VertexY",		"点坐标Y",						MDBFieldCategoryParam,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
};

static	tagMemDBField	g_PGSccFMoveFieldArray[]=
{
	{	PG_SCC_FMOVE_FAULTTYPE,			"FaultType",		"故障类型",					MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned	char),	sizeof(g_PGEnumFaultType)/sizeof(tagMemDBEnumPair),	g_PGEnumFaultType,	},
	{	PG_SCC_FMOVE_FAULTLINE,			"FaultLine",		"故障线路",					MDBFieldCategoryOutput,	MDB_STRING,	MDB_CHARLEN_LONG,		0,	NULL,	},
	{	PG_SCC_FMOVE_MONLINE,			"MonLine",			"监视线路",					MDBFieldCategoryOutput,	MDB_STRING,	MDB_CHARLEN_LONG,		0,	NULL,	},
	{	PG_SCC_FMOVE_MONBUS,			"MonBus",			"监视母线",					MDBFieldCategoryOutput,	MDB_STRING,	MDB_CHARLEN_LONG,		0,	NULL,	},
	{	PG_SCC_FMOVE_DATATYPE,			"DataType",			"数据类型",					MDBFieldCategoryOutput,	MDB_BIT,	sizeof(unsigned	char),	sizeof(g_PGEnumSccFMoveDataType)/sizeof(tagMemDBEnumPair),	g_PGEnumSccFMoveDataType,	},
	{	PG_SCC_FMOVE_VALUE000,			"Value000",			"值000",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE001,			"Value001",			"值001",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE002,			"Value002",			"值002",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE003,			"Value003",			"值003",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE004,			"Value004",			"值004",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE005,			"Value005",			"值005",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE006,			"Value006",			"值006",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE007,			"Value007",			"值007",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE008,			"Value008",			"值008",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE009,			"Value009",			"值009",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE010,			"Value010",			"值010",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE011,			"Value011",			"值011",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE012,			"Value012",			"值012",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE013,			"Value013",			"值013",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE014,			"Value014",			"值014",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE015,			"Value015",			"值015",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE016,			"Value016",			"值016",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE017,			"Value017",			"值017",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE018,			"Value018",			"值018",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE019,			"Value019",			"值019",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE020,			"Value020",			"值020",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE021,			"Value021",			"值021",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE022,			"Value022",			"值022",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE023,			"Value023",			"值023",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE024,			"Value024",			"值024",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE025,			"Value025",			"值025",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE026,			"Value026",			"值026",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE027,			"Value027",			"值027",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE028,			"Value028",			"值028",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE029,			"Value029",			"值029",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE030,			"Value030",			"值030",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE031,			"Value031",			"值031",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE032,			"Value032",			"值032",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE033,			"Value033",			"值033",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE034,			"Value034",			"值034",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE035,			"Value035",			"值035",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE036,			"Value036",			"值036",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE037,			"Value037",			"值037",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE038,			"Value038",			"值038",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE039,			"Value039",			"值039",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE040,			"Value040",			"值040",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE041,			"Value041",			"值041",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE042,			"Value042",			"值042",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE043,			"Value043",			"值043",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE044,			"Value044",			"值044",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE045,			"Value045",			"值045",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE046,			"Value046",			"值046",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE047,			"Value047",			"值047",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE048,			"Value048",			"值048",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE049,			"Value049",			"值049",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE050,			"Value050",			"值050",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE051,			"Value051",			"值051",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE052,			"Value052",			"值052",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE053,			"Value053",			"值053",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE054,			"Value054",			"值054",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE055,			"Value055",			"值055",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE056,			"Value056",			"值056",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE057,			"Value057",			"值057",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE058,			"Value058",			"值058",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE059,			"Value059",			"值059",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE060,			"Value060",			"值060",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE061,			"Value061",			"值061",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE062,			"Value062",			"值062",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE063,			"Value063",			"值063",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE064,			"Value064",			"值064",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE065,			"Value065",			"值065",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE066,			"Value066",			"值066",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE067,			"Value067",			"值067",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE068,			"Value068",			"值068",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE069,			"Value069",			"值069",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE070,			"Value070",			"值070",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE071,			"Value071",			"值071",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE072,			"Value072",			"值072",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE073,			"Value073",			"值073",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE074,			"Value074",			"值074",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE075,			"Value075",			"值075",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE076,			"Value076",			"值076",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE077,			"Value077",			"值077",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE078,			"Value078",			"值078",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE079,			"Value079",			"值079",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE080,			"Value080",			"值080",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE081,			"Value081",			"值081",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE082,			"Value082",			"值082",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE083,			"Value083",			"值083",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE084,			"Value084",			"值084",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE085,			"Value085",			"值085",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE086,			"Value086",			"值086",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE087,			"Value087",			"值087",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE088,			"Value088",			"值088",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE089,			"Value089",			"值089",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE090,			"Value090",			"值090",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE091,			"Value091",			"值091",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE092,			"Value092",			"值092",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE093,			"Value093",			"值093",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE094,			"Value094",			"值094",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE095,			"Value095",			"值095",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE096,			"Value096",			"值096",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE097,			"Value097",			"值097",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE098,			"Value098",			"值098",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE099,			"Value099",			"值099",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
	{	PG_SCC_FMOVE_VALUE100,			"Value100",			"值100",					MDBFieldCategoryOutput,	MDB_DOUBLE,	sizeof(double),			0,	NULL,	},
};
