#pragma once

static	tagMemDBField	g_PGElectronicTransformerFieldArray[]=
{
	{	PG_ELECTRONICTRANSFORMER_RESOURCEID,				"ResourceID",			"资源Id",					MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_SUBSTATION,				"Substation",			"厂站",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_NAME,						"Name",					"名称",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_DESC,						"Description",			"描述",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_ADCONVERTERNUM,			"ACConverterNum",		"交流变换器数",				MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_DDCONVERTERNUM,			"DCConverterNum",		"直流变换器数",				MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_VOLTAGELEVELACH,			"VoltagelevelACH",		"交流高电压等级",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_VOLTAGELEVELACL1,			"VoltagelevelACL1",		"交流低电压等级1",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_VOLTAGELEVELACL2,			"VoltagelevelACL2",		"交流低电压等级2",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_VOLTAGELEVELDCL1,			"VoltagelevelDCL1",		"直流低电压等级1",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_VOLTAGELEVELDCL2,			"VoltagelevelDCL2",		"直流低电压等级2",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_VOLTAGELEVELDCT,			"VoltagelevelDCT",		"直流中性点电压等级",		MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_ADCONVERTERH,				"ADConverterH",			"高压交直变换器",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_ADCONVERTERL1,				"ADConverterL1",		"低压交直变换器1",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_ADCONVERTERL2,				"ADConverterL2",		"低压交直变换器2",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_DDCONVERTERL1,				"DDConverterL1",		"低压直直变换器1",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_DDCONVERTERL2,				"DDConverterL2",		"低压直直变换器2",			MDBFieldCategoryParam,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_CONNECTIVITYNODEACH,		"ConnectivityNodeACH",	"高压交流节点",				MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_CONNECTIVITYNODEACL1,		"ConnectivityNodeACL1",	"低压交流节点1",			MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_CONNECTIVITYNODEACL2,		"ConnectivityNodeACL2",	"低压交流节点2",			MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_CONNECTIVITYNODEDCL1,		"ConnectivityNodeDCL1",	"低压直流节点1",			MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_CONNECTIVITYNODEDCL2,		"ConnectivityNodeDCL2",	"低压直流节点2",			MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_CONNECTIVITYNODEDCT,		"ConnectivityNodeDCT",	"直流中性点",				MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},

	{	PG_ELECTRONICTRANSFORMER_RI_RERR,					"ri_Rerr",				"故障率(次/年)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_RI_TREP,					"ri_Trep",				"修复时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_RI_RCHK,					"ri_Rchk",				"计划检修率(次/年)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_RI_TCHK,					"ri_Tchk",				"检修时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_RI_TFLOC,					"ri_Tfloc",				"故障定位隔离时间(小时)",	MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_EI_INVEST,					"ei_Invest",			"投资费用(万元)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_RO_RCONTRIBUTION,			"ro_RContribution",		"停运率贡献(%)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_RO_UCONTRIBUTION,			"ro_UContribution",		"停运时间贡献(%)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_RO_ENSCONTRIBUTION,		"ro_EnsContribution",	"停电电量贡献(%)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},

	{	PG_ELECTRONICTRANSFORMER_VOLTACHPTR,				"VoltACHPtr",			"交流高电压等级索引",		MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_VOLTACL1PTR,				"VoltACL1Ptr",			"交流低电压等级1索引",		MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_VOLTACL2PTR,				"VoltACL2Ptr",			"交流低电压等级2索引",		MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_VOLTDCL1PTR,				"VoltDCL1Ptr",			"直流低电压等级1索引",		MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_VOLTDCL2PTR,				"VoltDCL2Ptr",			"直流低电压等级2索引",		MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_VOLTDCTPTR,				"VoltDCTPtr",			"直流中性点电压等级索引",	MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},

	{	PG_ELECTRONICTRANSFORMER_ADCONVERTERHPTR,			"ADConverterHPtr",		"高压交直变换器索引",		MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_ADCONVERTERL1PTR,			"ADConverterL1Ptr",		"低压交直变换器1索引",		MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_ADCONVERTERL2PTR,			"ADConverterL2Ptr",		"低压交直变换器2索引",		MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_DDCONVERTERL1PTR,			"DDConverterL1Ptr",		"低压直直变换器1索引",		MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_DDCONVERTERL2PTR,			"DDConverterL2Ptr",		"低压直直变换器2索引",		MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},

	{	PG_ELECTRONICTRANSFORMER_NODEACHPTR,				"NodeACHPtr",			"高压交流节点索引",			MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_NODEACL1PTR,				"NodeACL1Ptr",			"低压交流节点1索引",		MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_NODEACL2PTR,				"NodeACL2Ptr",			"低压交流节点2索引",		MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_NODEDCL1PTR,				"NodeDCL1Ptr",			"低压直流节点1索引",		MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_NODEDCL2PTR,				"NodeDCL2Ptr",			"低压直流节点2索引",		MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_ELECTRONICTRANSFORMER_NODEDCTPTR,				"NodeDCTPtr",			"直流中性点索引",			MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
};

static	tagMemDBField	g_PGDCBusbarSectionFieldArray[]=
{
	{	PG_DCBUSBARSECTION_RESOURCEID,					"ResourceID",			"资源Id",					MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCBUSBARSECTION_OBJECTID,					"ObjectID",				"ObjectId",					MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCBUSBARSECTION_SUBSTATION,					"Substation",			"厂站",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCBUSBARSECTION_VOLTAGELEVEL,				"VoltageLevel",			"电压等级",					MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_DCBUSBARSECTION_NAME,						"Name",					"名称",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCBUSBARSECTION_DESC,						"Description",			"描述",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	//{	PG_DCBUSBARSECTION_TERMINAL,					"Terminal",				"端点",						MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DCBUSBARSECTION_CONNECTIVITYNODE,			"ConnectivityNode",		"节点",						MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DCBUSBARSECTION_V,							"V",					"电压(千伏)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_VLIMITL,						"VLimitL",				"电压下限(千伏)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_VLIMITH,						"VLimitH",				"电压上限(千伏)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_EFERENCEV,					"ReferenceV",			"给定电压(千伏)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_RI_RERR,						"ri_Rerr",				"故障率(次/年)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_RI_TREP,						"ri_Trep",				"修复时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_RI_RCHK,						"ri_Rchk",				"计划检修率(次/年)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_RI_TCHK,						"ri_Tchk",				"检修时间(小时/次)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_RI_TFLOC,					"ri_Tfloc",				"故障定位隔离时间(小时)",	MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_EI_INVEST,					"ei_Invest",			"投资费用(万元)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_RO_RCONTRIBUTION,			"ro_RContribution",		"停运率贡献(%)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_RO_UCONTRIBUTION,			"ro_UContribution",		"停运时间贡献(%)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_RO_ENSCONTRIBUTION,			"ro_EnsContribution",	"停电电量贡献(%)",			MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_NODEPTR,						"NodePtr",				"节点索引",					MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_TOPOBUS,						"TopoBus",				"拓扑节点",					MDBFieldCategoryTopo,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_ISLAND,						"Island",				"岛",						MDBFieldCategoryTopo,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCBUSBARSECTION_OPEN,						"Open",					"拓扑状态",					MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
};

static	tagMemDBField	g_PGACDCConverterFieldArray[]=
{
	{	PG_ACDCCONVERTER_RESOURCEID,				"ResourceID",			"资源Id",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ACDCCONVERTER_SUBSTATION,				"Substation",			"厂站",								MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ACDCCONVERTER_NAME,						"Name",					"名称",								MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ACDCCONVERTER_DESC,						"Description",			"描述",								MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ACDCCONVERTER_VOLTAGELEVELAC,			"VoltagelevelAC",		"交流电压等级",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_ACDCCONVERTER_VOLTAGELEVELDC,			"VoltagelevelDC",		"直流电压等级",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_ACDCCONVERTER_ECTRICTRANSFORMER,			"ElectronicTransformer","所属电力电子变压器",				MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_ACDCCONVERTER_ISOLATOR,					"Isolator",				"隔离器",							MDBFieldCategoryBase,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumNoYes)/sizeof(tagMemDBEnumPair),					g_PGEnumNoYes,	},
	//{	PG_ACDCCONVERTER_TERMINALAC,				"TerminalAC",			"交流端点",							MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	//{	PG_ACDCCONVERTER_TERMINALDC,				"TerminalDC",			"直流端点",							MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_ACDCCONVERTER_CONNECTIVITYNODEAC,		"ConnectivityNodeAC",	"交流节点",							MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_ACDCCONVERTER_CONNECTIVITYNODEDC,		"ConnectivityNodeDC",	"直流节点",							MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_ACDCCONVERTER_RATEDPOWER,				"RatedPower",			"额定容量(兆瓦)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_MINQ,						"MinQ",					"最小无功(兆乏)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_MAXQ,						"MaxQ",					"最大无功(兆乏)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_DCCONTROLMODE,				"DCControlMode",		"直流侧控制模式",					MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumConverterDCControlMode)/sizeof(tagMemDBEnumPair),	g_PGEnumConverterDCControlMode,	},
	{	PG_ACDCCONVERTER_DCCONTROLVALUE,			"DCControlValue",		"直流侧控制值(电压标幺,功率兆瓦)",	MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_CONTROLVAC,				"ControlVac",			"交流侧电压控制值(标幺)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_LOSSPARAMA,				"LossParamA",			"损耗多项式参数(a)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_LOSSPARAMB,				"LossParamB",			"损耗多项式参数(b)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_LOSSPARAMC,				"LossParamC",			"损耗多项式参数(c)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_RI_RERR,					"ri_Rerr",				"故障率(次/台.年)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_RI_TREP,					"ri_Trep",				"修复时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_RI_RCHK,					"ri_Rchk",				"计划检修率(次/台.年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_RI_TCHK,					"ri_Tchk",				"检修时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_RI_TFLOC,					"ri_Tfloc",				"故障定位隔离时间(小时)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_RI_DIRECTION,				"ri_Direction",			"供电方向",							MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumBranchFlow_Direction)/sizeof(tagMemDBEnumPair),	g_PGEnumBranchFlow_Direction,	},
	{	PG_ACDCCONVERTER_EI_INVEST,					"ei_Invest",			"投资费用(万元)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_MCRTYPEAC,					"MCRTypeAC",			"交流主接线可靠性设备类型",			MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumBranchMCRDevType)/sizeof(tagMemDBEnumPair),						g_PGEnumBranchMCRDevType,	},
	{	PG_ACDCCONVERTER_MCRTYPEDC,					"MCRTypeDC",			"直流主接线可靠性设备类型",			MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumBranchMCRDevType)/sizeof(tagMemDBEnumPair),						g_PGEnumBranchMCRDevType,	},
	{	PG_ACDCCONVERTER_MCRPOWER,					"MCRPower",				"主接线可靠性源/荷功率",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_VAC,						"Vac",					"交流电压(千伏)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_PAC,						"Pac",					"交流有功(兆瓦)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_QAC,						"Qac",					"交流无功(兆乏)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_AAC,						"Aac",					"交流电流(安培)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_VDC,						"Vdc",					"直流电压(千伏)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_PDC,						"Pdc",					"直流有功(兆瓦)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_ADC,						"Adc",					"直流电流(安培)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_LOSS,						"Loss",					"损耗(兆瓦)",						MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_RO_RCONTRIBUTION,			"ro_RContribution",		"停运率贡献(%)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_RO_UCONTRIBUTION,			"ro_UContribution",		"停运时间贡献(%)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_RO_ENSCONTRIBUTION,		"ro_EnsContribution",	"停电电量贡献(%)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_CALCULATEPAC,				"CalculatePac",			"交流侧有功计算值(兆瓦)",			MDBFieldCategoryAid,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_CALCULATEQAC,				"CalculateQac",			"交流侧无功计算值(兆乏)",			MDBFieldCategoryAid,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_ACDCCONVERTER_VOLTACPTR,					"VoltACPTR",			"交流电压等级索引",					MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ACDCCONVERTER_VOLTDCPTR,					"VoltDCPTR",			"直流电压等级索引",					MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ACDCCONVERTER_NODEACPTR,					"NodeACPTR",			"交流节点索引",						MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_ACDCCONVERTER_NODEDCPTR,					"NodeDCPTR",			"直流节点索引"	,					MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_ACDCCONVERTER_TOPOBUSIAC,				"TopoBusAC",			"交流拓扑节点",						MDBFieldCategoryTopo,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_ACDCCONVERTER_TOPOBUSIDC,				"TopoBusDC",			"直流拓扑节点",						MDBFieldCategoryTopo,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_ACDCCONVERTER_ISLANDAC,					"IslandAC",				"交流侧电岛",						MDBFieldCategoryTopo,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ACDCCONVERTER_ISLANDDC,					"IslandDC",				"直流侧电岛",						MDBFieldCategoryTopo,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ACDCCONVERTER_EDGEAC,					"EdgeAC",				"交流边设备索引",					MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ACDCCONVERTER_EDGEDC,					"EdgeDC",				"直流边设备索引",					MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_ACDCCONVERTER_PSTATEAC,					"PStateAC",				"交流侧功率状态",					MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_ACDCCONVERTER_PSTATEDC,					"PStateDC",				"直流侧功率状态",					MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_ACDCCONVERTER_TYPE,						"Type",					"类型",								MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumConverterType)/sizeof(tagMemDBEnumPair),					g_PGEnumConverterType,	},
	{	PG_ACDCCONVERTER_OPEN,						"Open",					"拓扑状态",							MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_ACDCCONVERTER_OUTAGE,					"Outage",				"设备状态",							MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
};

static	tagMemDBField	g_PGDCDCConverterFieldArray[]=
{
	{	PG_DCDCCONVERTER_RESOURCEID,				"ResourceID",			"资源Id",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCDCCONVERTER_SUBSTATION,				"Substation",			"厂站",								MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCDCCONVERTER_NAME,						"Name",					"名称",								MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCDCCONVERTER_DESC,						"Description",			"描述",								MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCDCCONVERTER_VOLTAGELEVELI,				"iVoltageLevel",		"I侧电压等级",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_DCDCCONVERTER_VOLTAGELEVELJ,				"zVoltageLevel",		"J侧电压等级",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_DCDCCONVERTER_ECTRICTRANSFORMER,			"ElectronicTransformer","所属电力电子变压器",				MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCDCCONVERTER_ISOLATOR,					"Isolator",				"隔离器",							MDBFieldCategoryBase,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumNoYes)/sizeof(tagMemDBEnumPair),					g_PGEnumNoYes,	},
	//{	PG_DCDCCONVERTER_TERMINALI,					"TerminalI",			"I侧端点",							MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	//{	PG_DCDCCONVERTER_TERMINALJ,					"TerminalJ",			"J侧端点",		`					MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DCDCCONVERTER_CONNECTIVITYNODEI,			"ConnectivityNodeI",	"I侧节点",							MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DCDCCONVERTER_CONNECTIVITYNODEJ,			"ConnectivityNodeJ",	"J侧节点",							MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DCDCCONVERTER_RATEDPOWER,				"RatedPower",			"额定容量(兆瓦)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},

	{	PG_DCDCCONVERTER_CONTROLMODEI,				"ControlModeI",			"I侧控制模式",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumConverterDCControlMode)/sizeof(tagMemDBEnumPair),	g_PGEnumConverterDCControlMode,	},
	{	PG_DCDCCONVERTER_CONTROLVALUEI,				"ControlValueI",		"I侧控制值(电压标幺,功率兆瓦)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_CONTROLMODEJ,				"ControlModeJ",			"J侧控制模式",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumConverterDCControlMode)/sizeof(tagMemDBEnumPair),	g_PGEnumConverterDCControlMode,	},
	{	PG_DCDCCONVERTER_CONTROLVALUEJ,				"ControlValueJ",		"J侧控制值(电压标幺,功率兆瓦)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},

	{	PG_DCDCCONVERTER_LOSSPARAMA,				"LossParamA",			"损耗多项式参数(a)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_LOSSPARAMB,				"LossParamB",			"损耗多项式参数(b)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_LOSSPARAMC,				"LossParamC",			"损耗多项式参数(c)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_RI_RERR,					"ri_Rerr",				"故障率(次/台.年)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_RI_TREP,					"ri_Trep",				"修复时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_RI_RCHK,					"ri_Rchk",				"计划检修率(次/台.年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_RI_TCHK,					"ri_Tchk",				"检修时间(小时/次)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_RI_TFLOC,					"ri_Tfloc",				"故障定位隔离时间(小时)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_RI_DIRECTION,				"ri_Direction",			"供电方向",							MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumBranchFlow_Direction)/sizeof(tagMemDBEnumPair),	g_PGEnumBranchFlow_Direction,	},
	{	PG_DCDCCONVERTER_EI_INVEST,					"ei_Invest",			"投资费用(万元)",					MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_MCRTYPEI,					"MCRTypeI",				"I侧主接线可靠性设备类型",			MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumBranchMCRDevType)/sizeof(tagMemDBEnumPair),						g_PGEnumBranchMCRDevType,	},
	{	PG_DCDCCONVERTER_MCRTYPEJ,					"MCRTypeJ",				"J侧主接线可靠性设备类型",			MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumBranchMCRDevType)/sizeof(tagMemDBEnumPair),						g_PGEnumBranchMCRDevType,	},
	{	PG_DCDCCONVERTER_MCRPOWER,					"MCRPower",				"主接线可靠性源/荷功率",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_VI,						"Vi",					"I侧电压(千伏)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_PI,						"Pi",					"I侧有功(兆瓦)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_AI,						"Ai",					"I侧电流(安培)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_VJ,						"Vj",					"J侧电压(千伏)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_PJ,						"Pj",					"J侧有功(兆瓦)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_AJ,						"Aj",					"J侧电流(安培)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_LOSS,						"Loss",					"损耗(兆瓦)",						MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_RO_RCONTRIBUTION,			"ro_RContribution",		"停运率贡献(%)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_RO_UCONTRIBUTION,			"ro_UContribution",		"停运时间贡献(%)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_RO_ENSCONTRIBUTION,		"ro_EnsContribution",	"停电电量贡献(%)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_CALCULATEPI,				"CalculatePI",			"I侧功率计算值(兆瓦)",				MDBFieldCategoryAid,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_CALCULATEPJ,				"CalculatePJ",			"J侧功率计算值(兆瓦)",				MDBFieldCategoryAid,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCDCCONVERTER_VOLTIPTR,					"VoltITR",				"I侧电压等级索引",					MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCDCCONVERTER_VOLTJPTR,					"VoltJTR",				"J侧电压等级索引",					MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCDCCONVERTER_NODEIPTR,					"NodeIPTR",				"I侧节点索引",						MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCDCCONVERTER_NODEJPTR,					"NodeJPTR",				"J侧节点索引",						MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCDCCONVERTER_TOPOBUSI,					"TopoBusI",				"I侧拓扑节点",						MDBFieldCategoryTopo,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCDCCONVERTER_TOPOBUSJ,					"TopoBusJ",				"J侧拓扑节点",						MDBFieldCategoryTopo,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCDCCONVERTER_ISLANDI,					"IslandI",				"I侧岛",							MDBFieldCategoryTopo,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCDCCONVERTER_ISLANDJ,					"IslandJ",				"J侧岛",							MDBFieldCategoryTopo,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCDCCONVERTER_EDGEI,						"EdgeI",				"I侧边设备索引",					MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCDCCONVERTER_EDGEJ,						"EdgeJ",				"J侧边设备索引",					MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCDCCONVERTER_PSTATEI,					"PStateI",				"I侧功率状态",						MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_DCDCCONVERTER_PSTATEJ,					"PStateJ",				"J侧功率状态",						MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_DCDCCONVERTER_TYPE,						"Type",					"类型",								MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumConverterType)/sizeof(tagMemDBEnumPair),					g_PGEnumConverterType,	},
	{	PG_DCDCCONVERTER_OPEN,						"Open",					"拓扑状态",							MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_DCDCCONVERTER_OUTAGE,					"Outage",				"设备状态",							MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
};

static	tagMemDBField	g_PGDCBreakerFieldArray[]=
{
	{	PG_DCBREAKER_RESOURCEID,					"ResourceID",			"资源Id",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCBREAKER_OBJECTID,						"ObjectID",				"ObjectId",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCBREAKER_SUBSTATION,					"Substation",			"厂站",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCBREAKER_VOLTAGELEVEL,					"VoltageLevel",			"电压等级",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_DCBREAKER_NAME,							"Name",					"名称",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCBREAKER_DESC,							"Description",			"描述",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCBREAKER_STATUS,						"Status",				"运行状态",						MDBFieldCategoryParam,	MDB_BIT,	sizeof(unsigned char),	sizeof(g_PGEnumCloseOpenStatus)/sizeof(tagMemDBEnumPair),		g_PGEnumCloseOpenStatus,	},
	//{	PG_DCBREAKER_ITERMINAL,						"iTerminal",			"起端点",						MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	//{	PG_DCBREAKER_JTERMINAL,						"zTerminal",			"终端点",						MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DCBREAKER_CONNECTIVITYNODEI,				"ConnectivityNodeI",	"起节点",						MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DCBREAKER_CONNECTIVITYNODEJ,				"ConnectivityNodeJ",	"终节点",						MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DCBREAKER_RI_RERR,						"ri_Rerr",				"故障率(次/台.年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBREAKER_RI_TREP,						"ri_Trep",				"修复时间(小时/次)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBREAKER_RI_RCHK,						"ri_Rchk",				"计划检修率(次/台.年)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBREAKER_RI_TCHK,						"ri_Tchk",				"检修时间(小时/次)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBREAKER_RI_TFLOC,						"ri_Tfloc",				"故障定位隔离时间(小时)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBREAKER_RI_TSWITCH,					"ri_TSwitch",			"操作时间(小时/次)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBREAKER_EI_INVEST,						"ei_Invest",			"投资费用(万元)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBREAKER_P,								"P",					"有功(兆瓦)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBREAKER_A,								"A",					"电流(安培)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBREAKER_RO_RCONTRIBUTION,				"ro_RContribution",		"停运率贡献(%)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBREAKER_RO_UCONTRIBUTION,				"ro_UContribution",		"停运时间贡献(%)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBREAKER_RO_ENSCONTRIBUTION,			"ro_EnsContribution",	"停电电量贡献(%)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCBREAKER_NODEIPTR,						"NodeIPtr",				"起节点索引",					MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCBREAKER_NODEJPTR,						"NodeJPtr",				"终节点索引",					MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCBREAKER_ISLAND,						"Island",				"岛",							MDBFieldCategoryTopo,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCBREAKER_EDGEI,							"EdgeI",				"I侧边设备索引",				MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCBREAKER_EDGEJ,							"EdgeJ",				"J侧边设备索引",				MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCBREAKER_JOINTDEVICETYPE,				"JointDeviceType",		"控制设备类型",					MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_DCBREAKER_JOINTDEVICEINDEX,				"JointDeviceIndex",		"控制设备索引",					MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCBREAKER_OUTAGE,						"Outage",				"设备状态",						MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
};

static	tagMemDBField	g_PGDCShortCircuitLimitFieldArray[]=
{
	{	PG_DCSHORTCIRCUITLIMIT_RESOURCEID,			"ResourceID",			"资源Id",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_OBJECTID,			"ObjectID",				"ObjectId",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_SUBSTATION,			"Substation",			"厂站",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_VOLTAGELEVEL,		"VoltageLevel",			"电压等级",						MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN_SHORTER,	0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_NAME,				"Name",					"名称",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_DESC,				"Description",			"描述",							MDBFieldCategoryBase,	MDB_STRING,	MDB_CHARLEN,			0,	NULL,	},
	//{	PG_DCSHORTCIRCUITLIMIT_ITERMINAL,			"iTerminal",			"起端点",						MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	//{	PG_DCSHORTCIRCUITLIMIT_JTERMINAL,			"zTerminal",			"终端点",						MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_CONNECTIVITYNODEI,	"ConnectivityNodeI",	"起节点",						MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_CONNECTIVITYNODEJ,	"ConnectivityNodeJ",	"终节点",						MDBFieldCategoryTopo,	MDB_STRING,	PGND_CHARLEN,			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_R,					"R",					"等效电阻(标幺)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_RI_RERR,				"ri_Rerr",				"故障率(次/台.年)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_RI_TREP,				"ri_Trep",				"修复时间(小时/次)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_RI_RCHK,				"ri_Rchk",				"计划检修率(次/台.年)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_RI_TCHK,				"ri_Tchk",				"检修时间(小时/次)",			MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_RI_TFLOC,			"ri_Tfloc",				"故障定位隔离时间(小时)",		MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_EI_INVEST,			"ei_Invest",			"投资费用(万元)",				MDBFieldCategoryParam,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_PI,					"Pi",					"I侧有功(兆瓦)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_PJ,					"Pj",					"J侧有功(兆瓦)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_A,					"A",					"电流(安培)",					MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_LOSSP,				"LossP",				"损耗有功(兆瓦)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_RO_RCONTRIBUTION,	"ro_RContribution",		"停运率贡献(%)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_RO_UCONTRIBUTION,	"ro_UContribution",		"停运时间贡献(%)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_RO_ENSCONTRIBUTION,	"ro_EnsContribution",	"停电电量贡献(%)",				MDBFieldCategoryOutput,	MDB_FLOAT,	sizeof(float),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_NODEIPTR,			"NodeIPtr",				"起节点索引",					MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_NODEJPTR,			"NodeJPtr",				"终节点索引",					MDBFieldCategoryAid,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_TOPOBUSI,			"TopoBusI",				"起拓扑节点",					MDBFieldCategoryTopo,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_TOPOBUSJ,			"TopoBusJ",				"终拓扑节点",					MDBFieldCategoryTopo,	MDB_INT,	sizeof(int),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_ISLAND,				"Island",				"岛",							MDBFieldCategoryTopo,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_EDGEI,				"EdgeI",				"I侧边设备索引",				MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_EDGEJ,				"EdgeJ",				"J侧边设备索引",				MDBFieldCategoryAid,	MDB_SHORT,	sizeof(short),			0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_PROC,				"Proc",					"中间信息",						MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_OPEN,				"Open",					"拓扑状态",						MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
	{	PG_DCSHORTCIRCUITLIMIT_OUTAGE,				"Outage",				"设备状态",						MDBFieldCategoryAid,	MDB_BIT,	sizeof(unsigned char),	0,	NULL,	},
};
